fixtures:
  repositories:
    "facts": "https://github.com/puppetlabs/puppetlabs-facts.git"
    "provision": "https://github.com/puppetlabs/provision.git"
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.21.0
  symlinks:
    package: "#{source_dir}"

